apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: default
spec:
 ingressClassName: nginx
 rules:
 - host: myhost.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: keda-add-ons # <-- interceptor service
           port:
             number: 8080