apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: nginx
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 200
  scaleTargetRef:
    name: nginx
    kind: Deployment
    apiVersion: apps/v1
    service: nginx-service
    port: 80
  replicas:
    min: 0
    max: 5